### PR TITLE
Looker service

### PR DESCRIPTION
**Pull request by jpurpura**
# Fixes # 

### Checklist
- [ ] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [ ] I have read the [Contribution Guide] and my PR follows them.
- [ ] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added in line documentation to the code I modified

### Short description of what this PR does:
- adds a configurable service that retrieves and stores data from Looker via RESTful API

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/dx-automator?pullRequest=23) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/dx-automator?pullRequest=23) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: thinkingserious<br/>:white_check_mark: af4ro<br/>:x: jpurpura<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/dx-automator?pullRequest=23) it.</sub>

**Comment by thinkingserious** [comment]
Hi @jpurpura,

Could you please take a moment to [sign the CLA](https://cla.sendgrid.com/sendgrid/dx-automator?pullRequest=23) real quick. Thanks!

**Comment by thinkingserious** [comment]
Can you please add a quick README ([e.g.](https://github.com/af4ro/dx-automator/blob/react-client/services/client-react/README.md)) to the root of your project that explains installation and usage?

**Comment by thinkingserious** [comment]
Hello @jpurpura,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
